language: ruby
rvm:
 - 3.0.1
before_script:
  - npm install -g n stable
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
before_install:
  - gem update --system
  - gem --version
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install 12
  - node -v
  - npm i -g yarn
  - yarn
script:
  - RAILS_ENV=test ./bin/rails webpacker:compile
  - bundle exec  rspec spec
