language: ruby
rvm:
 - 3.0.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
before_install:
  - gem update --system
  - gem --version
script:
  - yarn
  - bundle exec  rspec spec
