env:
  - Node.js ">=10.17.0"
language: ruby
rvm:
 - 3.0.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
before_install:
  - gem update --system
  - gem --version
script:
  - RAILS_ENV=test ./bin/rails webpacker:compile
  - bundle exec  rspec spec
